### ISSUE TITLE
video feed (depth or rgb image) publishing leads to memory leak due to implementation of fixed queue size in rosjava_core 

### ISSUE THREAD

**Issue by nileshsuri** [mit-acl/android_loomo_ros_core#3]

**Comment by marshallrichards** [comment]
Hi @Nilesh-Suri , can you describe how you solved this issue? I am also running into the same problem. Thanks.

**Comment by nileshsuri** [comment]
> Hi @Nilesh-Suri , can you describe how you solved this issue? I am also running into the same problem. Thanks.

@marshallr3 for now I solved it by reducing the publishing frame rate and carrying out some compression. However a modification to the rosjava_core is needed to allow for dynamic sized queue. They currently use a static queue size of 16 for all message types. Hopefully it will be fixed in a future update.
